apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: whoami
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: whoami  # Matches the labels in your ServiceEntry endpoints
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami
  namespace: whoami
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`whoami.docker.localhost`)
      kind: Rule
      services:
        - name: whoami
          port: 80
          nativeLB: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami2
  namespace: whoami
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`whoami2.docker.localhost`)
      kind: Rule
      services:
        - name: whoami2
          port: 80
          nativeLB: true
---
apiVersion: v1
kind: Service
metadata:
  name: whoami2
  namespace: whoami
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: whoami2  # Matches the labels in your ServiceEntry endpoints
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami2
  namespace: whoami
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami2
  template:
    metadata:
      labels:
        app: whoami2
    spec:
      containers:
        - name: whoami
          image: traefik/whoami
          ports:
            - containerPort: 80
              name: http
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
spec:
  routes:
    - match: Host(`traefik.docker.localhost`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
