apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: whoami
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: whoami  # Matches the labels in your ServiceEntry endpoints
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: whoami-se
  namespace: whoami
spec:
  exportTo:
    - "*"
  hosts:
    - whoami.whoami.svc.cluster.local
  location: MESH_INTERNAL
  ports:
    - number: 80
      name: http
      protocol: HTTP
  resolution: STATIC
---
apiVersion: networking.istio.io/v1beta1
kind: WorkloadEntry
metadata:
  name: whoami-remote
  namespace: whoami
spec:
  address: 172.20.0.6  # Cluster 2 East-West Gateway
  network: network2
  labels:
    app: whoami        # This matches the Service selector
  serviceAccount: whoami
  ports:
    http: 15008        # HBONE tunnel port
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami
  namespace: whoami
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`whoami.docker.localhost`)
      kind: Rule
      services:
        - name: whoami
          port: 80
          nativeLB: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: helloworld
  namespace: sample
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`hello.docker.localhost`)
      kind: Rule
      services:
        - name: helloworld
          port: 5000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
spec:
  routes:
    - match: Host(`traefik.docker.localhost`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
